### ISSUE TITLE
Provide HTTP endpoint to get a new flake/id

### ISSUE THREAD

**Issue by eric** [Factual/skuld#108]
It would be helpful to be able for an HTTP client to get back a `flake/id` that it can provide an `:id` for `enqueue` to allow the client to retry until it gets a successful response.

**Comment by danielcompton** [comment]
Would this affect ordering? It could make reasoning about the order that messages were received difficult if a flake is taken ahead of time. Perhaps not so much in Skuld but more so in further downstream systems.

**Comment by aphyr** [comment]
It's a concurrent queue; what ordering guarantees do you think we can actually offer? ;-)
