### ISSUE TITLE
Start zookeeper as a part of the test suite

### ISSUE THREAD

**Issue by ghost** [Factual/skuld#21]
We can't run on Travis-CI until the test suite runs its own ZK. Should add zookeeper to the dev dependencies and start it if we can't connect to the local port.

**Comment by eric** [comment]
Inspiration: https://github.com/twitter/commons/blob/master/src/java/com/twitter/common/zookeeper/testing/ZooKeeperTestServer.java

**Comment by ghost** [comment]
Done!

**Comment by eric** [comment]
:dancers:
