### ISSUE TITLE
Named queues

### ISSUE THREAD

**Issue by ghost** [Factual/skuld#8]
Pretty straightforward; add a :queue field to each task, and modify the claim/list/count/etc logic to take queues into account.

**Comment by joelkuiper** [comment]
Should this still wait for the priority queue (I remember this being a dependency as discussed on irc.)

**Comment by ghost** [comment]
I've been down in the weeds on merkle tree/hashing stuff for the last month, so I actually _don't remember_, haha! There is a prioqueue implementation now in skuld.queue, and it's hooked up to skuld.node, but IIRC there are a few housekeeping things around the queue that may not work right yet.

**Comment by eric** [comment]
I'm trying to figure out the best way for this to work.

@aphyr: Were you intending on a single set of nodes/vnodes that would hold the tasks for all of the named queues?

**Comment by aphyr** [comment]
Naw, every node hosts every named queue.

**Comment by eric** [comment]
I spent a few minutes looking at what the interface change would look like, and it looks to me that only a few things in `vnode` are going to need to be aware of queue names:
- `vnode/count-queue`
- `vnode/claim!`
