### ISSUE TITLE
Question: How does :last-leader-msg-time stay up-to-date on a vnode leader?

### ISSUE THREAD

**Issue by eric** [Factual/skuld#81]
I've been reading through logs of test runs and noticed `"leader is outdated"` messages coming from the vnode master.

It made me look at the code and realize I couldn't find where `:last-leader-msg-time` is ever updated on the vnode master. Does this mean a leader is going to lose it's leadership every 10 seconds and have to get it again?

When a leader attempts to be re-elected, the [`:type` changes from `:leader` to `:candidate`](https://github.com/Factual/skuld/blob/8f00a3fce036479c3342fab28105c1f97de61798/src/skuld/vnode.clj#L300-L303), which means that it can't continue serving tasks for that vnode.

I believe that would mean that every 10 seconds a client would get a `nil` back from `get-claim`.

Am I reading this correctly?

**Comment by aphyr** [comment]
Yeah, sooooo this is _correct_ as far as the leader algo is concerned, but we should make ownership stable. Honestly, this algo will take a few weeks for me to get back up to speed on; lots of subtle stuff I forgot about. My guess is that suppressing re-election on the current primary is safe. Might break during quorum transition though.

**Comment by eric** [comment]
Okay,

The more I look at this code (now that I've had 5 different false assumptions as to why the tests are failing), I'm leaning towards believing it's the `:leader` -> `:candidate` -> `:leader` flip-flopping that is causing a lot of these random failures.

**Comment by aphyr** [comment]
Entirely possible. We should maintain a stable leader in the absence of quorum loss! Just not sure where the safe place to do it is.

**Comment by eric** [comment]
So I started to look at what it would mean to run an election if the `last-leader-msg-time` was more than half of `election-timeout`, and use that to increase `last-leader-msg-time`, but then realized that `elect!` [changes the state to `:canditate`](https://github.com/Factual/skuld/blob/3f4696f4686092695e38e603d80c8b31bd4b9759/src/skuld/vnode.clj#L308-L316) because it increases the epoch.

So... it makes me realize maybe the logic is entirely different in the case that a leader is just trying to re-up itself.

In reading through the the election code, it looks to me that an `epoch` will never be valid for more than `election-timeout`. Or to state it a different way, `epoch` will increment at least every `election-timeout` milliseconds. Is that accurate?

**Comment by aphyr** [comment]
Yeah. Might refer to the VR or RAFT papers here. Been a bit since I've thought about stability.

**Comment by eric** [comment]
We're using heartbeats now to keep the time up-to-date on the followers. The leader has no reason to check the time (because it knows it's alive).
