### ISSUE TITLE
Question: Should there be a exception type for vnode claim failures?

### ISSUE THREAD

**Issue by eric** [Factual/skuld#84]
In `vnode/claim!` there are [a few exceptions that are thrown](https://github.com/Factual/skuld/blob/fa03ff0e81988a227a4cc8ffef494fe73d9a12cb/src/skuld/vnode.clj#L486-L519) that will happen from time to time due to topology changes.

It would be nice to catch these in [`node/claim-local!`](https://github.com/Factual/skuld/blob/fa03ff0e81988a227a4cc8ffef494fe73d9a12cb/src/skuld/node.clj#L309-L311) and print a log message without a stack trace (because these things happen).

Should I use `IllegalStateException` for all 3 or should I create a differently named exception?

**Comment by aphyr** [comment]
ex-info might be most appropriate, but IllegalStateException is fine by me!

**Comment by eric** [comment]
I've done this in #85.
