### ISSUE TITLE
Question: Is it valid for a claim to be completed after the end time?

### ISSUE THREAD

**Issue by eric** [Factual/skuld#90]
I've found a random test failure in #87 and it's lead me to wonder a couple things:
1. Should it be possible to complete a claim after the end time?
2. Should it be possible to complete a claim without a start and end time?

**Comment by aphyr** [comment]
Yes and yes.

**Comment by aphyr** [comment]
(completions only occur after side effects have taken place; ignoring the completion will only cause duplication of side effects)

**Comment by eric** [comment]
Okay. I'll back out the validation and in #91 and make merge work with nil values.
